### ISSUE TITLE
Fails to work on wine/proton

### ISSUE THREAD

**Issue by gitdunk** [PrincessRTFM/CowtasticCafeEasyMode#1]
Doesn't work on wine, even tried changing path in doorstop config to an absolute path, game version is 1.1.0.1

**Comment by VariableVixen** [comment]
When a Unity game looks for a library on Windows, it first looks in the game's root directory. If it's found there, it uses that one; if not, it falls back to the system version. Doorstop uses this to inject its loader by proxying `winhttp.dll` in the game's own directory. On wine/proton, this does not happen by default, which prevents the Doorstop hook from being seen when the game launches.

You need to configure wine to load the "native" version (from the game directory) before the "builtin" version (from wine itself) in order for doorstop to load, which is required to make this mod load. As I don't use wine, I'm afraid I can't help you with this, but since this is a known issue for a number of unity-based steam games using doorstop for mod loaders, you should be able to find more details if you look around. The best I was able to find by searching around on github was for [a steam game called My Summer Car](https://github.com/piotrulos/MSCModLoader/discussions/135), using `winecfg` from the terminal with several environment variable overrides; there may be better tutorials, but you'll have to find them yourself.

**Comment by gitdunk** [comment]
Solved it! when installing [Tobey's BepInEx Pack for Subnautica](https://submodica.xyz/mods/sn1/141) it mentions using `WINEDLLOVERRIDES="winhttp=n,b" %command%` in the steam launch options, I tried the same for this and it worked, I tried wine, but it seems to have trouble with some of the features, it also makes the game unusable unless restarted if you tab out and back in. Steam uses their own version called proton and it works perfectly unlike wine, no tabbing issues nor lost menus.
